# Configuration file for storing 
# key hyperparameters of the CNN
# and Vision Transformer models
hyperparameters_CNN:

in_features = 784
out_features = 121
lr = 1e-3
epochs = 5

hyperparameters_ViT:
lr = 1e-3
epochs = 5
img_shape = (160,106)
in_channels = 4
patch_shape = (32,53)
d_model = 512
num_transformer_layers = 2
dropout_rate = 0.2
mlp_size = 1048
num_heads = 4
num_classes = 1
batch_size = 16
