wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705413271.679552
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      3:
      - 1
      - 17
      - 23
      - 37
      4: 3.10.9
      5: 0.16.2
      6: 4.24.0
      8:
      - 4
      - 5
      13: darwin-arm64
lr:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 8
