#Configuration file to keep track
#of hyperparameters of the Vision
#Transformer and CNN Models.
hyperparameters_ViT:

img_shape = (160,106)
in_channels = 4
patch_shape = (32,53)
d_model = 512
num_transformer_layers = 2
dropout_rate = 0.2
mlp_size = 1048
num_heads = 4
num_classes = 1
batch_size = 16
lr = 1e-3
epochs = 5

hyperparameters_CNN:

img_shape = (160,106)
in_channels = 4
out_features = 1
lr = 1e-3
epochs = 5
maxpool_dim = 2
kernel_size_layer1 = 4
kernel_size_layer2 = 2
conv_features_layer1 = 
conv_features_layer2 = 