wandb_version: 1

learning_rate:
  desc: null
  value: 0.029018821106778624
optimizer:
  desc: null
  value: sgd
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705336381.327302
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.11.5
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
